### ISSUE TITLE
Linear Extrapolation

### ISSUE THREAD

**Issue by stephenberry** [parsiad/mlinterp#1]
I'm wondering what the approach would be to implement linear extrapolation for out of bounds access using this weighted approach. Do you have any helpful tips for starting?

**Comment by parsiad** [comment]
I'm inclined to think that there isn't a natural extension of the weighted approach to extrapolation. 

What is the application you had in mind? There are many ways to extrapolate, and some may be more appropriate than others depending on the application.

**Comment by stephenberry** [comment]
Thanks for your reply. I tend to agree that the weighted approach doesn't extend to extrapolation.
Are there performance reasons for doing a weighted approach versus slope-based interpolation?

I'm currently writing N-dimensional table lookup code. And, I liked a lot of your approach, and how it easily supports multi-input interpolation. The aim is to allow the user to select the out of bounds behavior of the lookup: error, constant handling, or extrapolation. The immediate application is aerospace table lookups. Performance is critical.

**Comment by parsiad** [comment]
The weighted approach uses a convex combination of 2^N data points (N being the dimension).

I'm surprised you need more than 3 dimensions for aerospace. If you don't, I would consider writing an efficient 1-3 dimensional version.

**Comment by stephenberry** [comment]
Thanks for the feedback. I think we should be fine with first order truncation error rather than second order.
I'll probably write efficient cases for 1-3 dimensions and then have an N-dimensional generic case. We do use 4 dimensional cases and I'm working on another project that may require much higher dimensions. I'll start my own repository for the code. I can share it in this thread it you'd like to look at it.

You can close this issue. I really appreciate your help!

**Comment by parsiad** [comment]
I look forward to seeing the results!
