### ISSUE TITLE
Order related query

### ISSUE THREAD

**Issue by ghansham** [parsiad/mlinterp#9]
From the readme, I could make out that natural order is column major order (Fortan/Matlab style) as compared to row major order (C, C++,python, Java and most of the image data is stored in row major order). Is there any performance penalty between the two order usage? Do we have any documentation related to performance benchmarks?

**Comment by parsiad** [comment]
The two should be comparable in performance (see https://github.com/parsiad/mlinterp/blob/master/mlinterp/mlinterp.hpp#L94-L122), but I have not checked. It would be interesting to look at the assembly and/or benchmark, if you are up to it.

**Comment by ghansham** [comment]
If I will test it, will let you know. Not very sure. Only point was about doing contiguous memory access for large arrays so that swaping doesn't affect performance. The good part is you have kept it configurable. And one more point are the interp methods MT safe?

**Comment by parsiad** [comment]
Consider the following example:
```c
interp(
	nd, ni,        // Number of points
	zd, zi,        // Output axis (z)
	xd, xi, yd, yi // Input axes (x and y)
);
```
The only buffer that is written to is `zi`. The other buffers (in this case, `zd`, `xd`, `xi`, `yd`, `yi`) are read-only and can be shared among threads.
